### ISSUE TITLE
Be consistent with styling method

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/antonio-project-week-6#9]
You have used a mix of global CSS classes and inline Javascript styles. For this project please try to be consistent and either use inline styles throughout (for example I can see styles for the discs in the global CSS, but this could be placed in the module where the disc component lives) or use CSS modules throughout (https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/)

It's great that you're separating your styles out from your component structure, however It is somewhat misleading to call your files e.g. `board-players.css.js` as this leads to importing as `board-players.css` while the file is actually JS and contains an object and JS style properties, not CSS. If you want to define your styles in a JS object that is totally fine, but perhaps use the suffix `.styles.js` instead of `.css.js`

**Comment by AntonioGargaro** [comment]
Updated file naming conventions to `name.style.js` for inline styles. Global CSS file still used for fonts and other general stylings.
